services:
  web: 
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./library:/ .
    environment:
      - DB_HOST=db
      - DB_NAME=db01
      - DB_USER=merkul
      - DB_PASS=merkul12
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=db01
      - POSTGRES_USER=merkul
      - POSTGRES_PASSWORD=merkul12
  redis:
    image: redis:latest

  celery:
    build:
      context: .
    command: celery -A library worker -l info
    volumes:
      - ./library:/ .
    depends_on:
      - redis